export default function TermsPage() {
  return (
    <div className="legal-page">
    <h1>Terms of Service</h1>
    <p><strong>Last Updated:</strong> June 19, 2026</p>

    <p>Welcome to Tensor. By accessing or using our Progressive Web Application (PWA) available at tensor.fit, you agree to be bound by these Terms of Service.</p>

    <h2>1. Use of the Application</h2>
    <p>Tensor provides a local workout tracking utility. The app is provided "as is" and "as available". You are fully responsible for how you use the app and manage your local data backups.</p>

    <h2>2. Medical and Fitness Disclaimer</h2>
    <p>Tensor is a tracking tool, not a medical professional or certified personal trainer. <strong>Any fitness plans or analytical suggestions generated by the app are for informational purposes only.</strong> Consult a physician before starting any weightlifting or strenuous exercise program. You assume all risks associated with physical injuries that may occur during your workouts.</p>

    <h2>3. Subscriptions and Payments (Tensor Pro)</h2>
    <ul>
        <li><strong>Billing:</strong> Subscriptions are billed on a recurring monthly or annual basis via Paddle.com.</li>
        <li><strong>Cancellations:</strong> You can cancel your subscription at any time via the "Manage Subscription" portal in the application settings. Upon cancellation, you will retain Pro access until the end of your current billing cycle.</li>
        <li><strong>Refunds:</strong> Refund policies are governed by Paddle's terms and applicable European/Swiss consumer protection laws.</li>
    </ul>

    <h2>4. Data Loss Risk</h2>
    <p>Because Tensor stores data locally on your device (SQLite/OPFS) for privacy reasons, <strong>uninstalling your browser, clearing your website data, restoring your phone, or losing your device will result in the permanent loss of your data</strong> unless you have previously exported a manual backup file. We are not responsible for any data loss.</p>

    <h2>5. Governing Law</h2>
    <p>These Terms shall be governed by and construed in accordance with the laws of Switzerland, without regard to its conflict of law provisions.</p>

    <h2>6. Modifications</h2>
    <p>We reserve the right to modify these terms at any time. Continued use of the app after changes implies acceptance of the new Terms.</p>
    </div>
  );
}
